[2025-01-15T19:04:11.947+0000] {processor.py:186} INFO - Started process (PID=64) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:04:11.949+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:04:11.952+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:04:11.952+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:04:11.989+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:04:11.984+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-15T19:04:11.991+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:04:12.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.073 seconds
[2025-01-15T19:04:42.310+0000] {processor.py:186} INFO - Started process (PID=134) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:04:42.312+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:04:42.316+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:04:42.316+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:04:42.352+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:04:42.345+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-15T19:04:42.355+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:04:42.395+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.095 seconds
[2025-01-15T19:05:12.610+0000] {processor.py:186} INFO - Started process (PID=198) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:05:12.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:05:12.615+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:05:12.615+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:05:12.639+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:05:12.635+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-15T19:05:12.642+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:05:12.665+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.062 seconds
[2025-01-15T19:05:42.836+0000] {processor.py:186} INFO - Started process (PID=262) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:05:42.838+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:05:42.841+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:05:42.840+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:05:42.869+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:05:42.864+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-15T19:05:42.873+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:05:42.903+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.074 seconds
[2025-01-15T19:06:13.278+0000] {processor.py:186} INFO - Started process (PID=326) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:06:13.279+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:06:13.283+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:06:13.282+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:06:13.311+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:06:13.305+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-15T19:06:13.313+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:06:13.340+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.068 seconds
[2025-01-15T19:06:43.455+0000] {processor.py:186} INFO - Started process (PID=390) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:06:43.457+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:06:43.459+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:06:43.459+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:06:43.488+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:06:43.483+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-15T19:06:43.491+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:06:43.515+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.065 seconds
[2025-01-15T19:07:14.049+0000] {processor.py:186} INFO - Started process (PID=454) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:07:14.050+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:07:14.053+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:07:14.053+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:07:14.080+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:07:14.074+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-15T19:07:14.083+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:07:14.107+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.064 seconds
[2025-01-15T19:07:44.240+0000] {processor.py:186} INFO - Started process (PID=518) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:07:44.242+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:07:44.245+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:07:44.245+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:07:44.270+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:07:44.265+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-15T19:07:44.273+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:07:44.304+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.070 seconds
[2025-01-15T19:08:15.001+0000] {processor.py:186} INFO - Started process (PID=582) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:08:15.002+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:08:15.005+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:08:15.004+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:08:15.033+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:08:15.028+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-15T19:08:15.035+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:08:15.059+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.065 seconds
[2025-01-15T19:08:45.751+0000] {processor.py:186} INFO - Started process (PID=646) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:08:45.753+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:08:45.756+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:08:45.756+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:08:45.782+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:08:45.777+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-15T19:08:45.786+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:08:45.810+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.065 seconds
[2025-01-15T19:09:16.005+0000] {processor.py:186} INFO - Started process (PID=710) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:09:16.008+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:09:16.013+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:09:16.012+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:09:16.050+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:09:16.042+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-15T19:09:16.054+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:09:16.079+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.080 seconds
[2025-01-15T19:09:47.045+0000] {processor.py:186} INFO - Started process (PID=774) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:09:47.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:09:47.050+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:09:47.050+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:09:47.077+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:09:47.072+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-15T19:09:47.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:09:47.104+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.067 seconds
[2025-01-15T19:10:17.328+0000] {processor.py:186} INFO - Started process (PID=838) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:10:17.329+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:10:17.332+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:10:17.332+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:10:17.356+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:10:17.352+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-15T19:10:17.358+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:10:17.384+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.062 seconds
[2025-01-15T19:11:19.806+0000] {processor.py:186} INFO - Started process (PID=70) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:11:19.808+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:11:19.813+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:11:19.813+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:11:19.919+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:11:19.905+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:11:19.925+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:11:19.953+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.158 seconds
[2025-01-15T19:11:50.749+0000] {processor.py:186} INFO - Started process (PID=134) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:11:50.751+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:11:50.754+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:11:50.753+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:11:50.817+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:11:50.804+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:11:50.821+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:11:50.852+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.109 seconds
[2025-01-15T19:12:21.129+0000] {processor.py:186} INFO - Started process (PID=198) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:12:21.131+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:12:21.134+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:12:21.133+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:12:21.202+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:12:21.189+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:12:21.208+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:12:21.237+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.115 seconds
[2025-01-15T19:12:51.480+0000] {processor.py:186} INFO - Started process (PID=262) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:12:51.481+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:12:51.484+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:12:51.484+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:12:51.545+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:12:51.534+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:12:51.549+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:12:51.576+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.101 seconds
[2025-01-15T19:13:21.705+0000] {processor.py:186} INFO - Started process (PID=327) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:13:21.708+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:13:21.711+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:13:21.710+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:13:21.791+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:13:21.774+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:13:21.795+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:13:21.820+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.132 seconds
[2025-01-15T19:13:52.045+0000] {processor.py:186} INFO - Started process (PID=396) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:13:52.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:13:52.050+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:13:52.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:13:52.118+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:13:52.106+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:13:52.122+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:13:52.150+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.110 seconds
[2025-01-15T19:14:22.339+0000] {processor.py:186} INFO - Started process (PID=460) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:14:22.340+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:14:22.344+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:14:22.344+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:14:22.427+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:14:22.413+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:14:22.432+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:14:22.463+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.133 seconds
[2025-01-15T19:14:52.699+0000] {processor.py:186} INFO - Started process (PID=524) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:14:52.700+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:14:52.703+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:14:52.702+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:14:52.763+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:14:52.751+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:14:52.767+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:14:52.792+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.099 seconds
[2025-01-15T19:15:22.819+0000] {processor.py:186} INFO - Started process (PID=588) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:15:22.820+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:15:22.824+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:15:22.824+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:15:22.888+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:15:22.879+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:15:22.897+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:15:22.249+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.111 seconds
[2025-01-15T19:15:52.565+0000] {processor.py:186} INFO - Started process (PID=652) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:15:52.566+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:15:52.568+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:15:52.568+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:15:52.634+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:15:52.622+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:15:52.639+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:15:52.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.112 seconds
[2025-01-15T19:16:23.079+0000] {processor.py:186} INFO - Started process (PID=716) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:16:23.080+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:16:23.083+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:16:23.082+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:16:23.150+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:16:23.138+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:16:23.154+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:16:23.176+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.105 seconds
[2025-01-15T19:16:54.029+0000] {processor.py:186} INFO - Started process (PID=780) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:16:54.031+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:16:54.034+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:16:54.034+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:16:54.104+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:16:54.093+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:16:54.108+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:16:54.130+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.107 seconds
[2025-01-15T19:17:24.995+0000] {processor.py:186} INFO - Started process (PID=844) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:17:24.996+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:17:25.000+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:17:24.999+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:17:25.080+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:17:25.064+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:17:25.086+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:17:25.112+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.124 seconds
[2025-01-15T19:17:56.126+0000] {processor.py:186} INFO - Started process (PID=908) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:17:56.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:17:56.131+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:17:56.130+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:17:56.203+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:17:56.189+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:17:56.208+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:17:56.231+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.110 seconds
[2025-01-15T19:18:26.762+0000] {processor.py:186} INFO - Started process (PID=972) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:18:26.765+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:18:26.770+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:18:26.769+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:18:26.858+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:18:26.838+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:18:26.865+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:18:26.906+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.155 seconds
[2025-01-15T19:18:57.752+0000] {processor.py:186} INFO - Started process (PID=1036) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:18:57.755+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:18:57.768+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:18:57.768+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:18:58.047+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:18:58.007+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:18:58.073+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:18:58.122+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.378 seconds
[2025-01-15T19:19:28.572+0000] {processor.py:186} INFO - Started process (PID=1100) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:19:28.573+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:19:28.576+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:19:28.575+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:19:28.643+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:19:28.632+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:19:28.648+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:19:28.672+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.106 seconds
[2025-01-15T19:19:59.298+0000] {processor.py:186} INFO - Started process (PID=1164) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:19:59.299+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:19:59.303+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:19:59.302+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:19:59.395+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:19:59.377+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:19:59.402+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:19:59.435+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.146 seconds
[2025-01-15T19:20:29.643+0000] {processor.py:186} INFO - Started process (PID=1228) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:20:29.645+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:20:29.649+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:20:29.648+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:20:29.725+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:20:29.711+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:20:29.730+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:20:29.756+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.119 seconds
[2025-01-15T19:23:33.061+0000] {processor.py:186} INFO - Started process (PID=77) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:23:33.064+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:23:33.069+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:23:33.068+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:23:33.254+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:23:33.177+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:23:33.260+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:23:33.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.275 seconds
[2025-01-15T19:24:03.749+0000] {processor.py:186} INFO - Started process (PID=141) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:24:03.754+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:24:03.779+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:24:03.777+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:24:03.975+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:24:03.959+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:24:03.981+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:24:04.110+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.430 seconds
[2025-01-15T19:24:34.629+0000] {processor.py:186} INFO - Started process (PID=205) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:24:34.631+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:24:34.634+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:24:34.634+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:24:34.703+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:24:34.690+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:24:34.708+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:24:34.736+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.115 seconds
[2025-01-15T19:25:04.940+0000] {processor.py:186} INFO - Started process (PID=269) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:25:04.941+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:25:04.948+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:25:04.947+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:25:05.019+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:25:05.009+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:25:05.025+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:25:05.055+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.122 seconds
[2025-01-15T19:25:35.124+0000] {processor.py:186} INFO - Started process (PID=333) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:25:35.125+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:25:35.129+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:25:35.129+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:25:35.198+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:25:35.185+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:25:35.203+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:25:35.228+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.110 seconds
[2025-01-15T19:26:05.315+0000] {processor.py:186} INFO - Started process (PID=397) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:26:05.316+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:26:05.320+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:26:05.319+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:26:05.383+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:26:05.373+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:26:05.388+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:26:05.416+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.106 seconds
[2025-01-15T19:26:36.439+0000] {processor.py:186} INFO - Started process (PID=461) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:26:36.445+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:26:36.456+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:26:36.450+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:26:36.573+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:26:36.549+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:26:36.582+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:26:36.638+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.236 seconds
[2025-01-15T19:27:07.034+0000] {processor.py:186} INFO - Started process (PID=525) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:27:07.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:27:07.039+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:27:07.038+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:27:07.111+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:27:07.097+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:27:07.116+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:27:07.140+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.111 seconds
[2025-01-15T19:27:37.746+0000] {processor.py:186} INFO - Started process (PID=589) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:27:37.747+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:27:37.750+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:27:37.749+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:27:37.808+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:27:37.797+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:27:37.812+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:27:37.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.094 seconds
[2025-01-15T19:28:07.997+0000] {processor.py:186} INFO - Started process (PID=653) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:28:07.998+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:28:08.001+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:28:08.001+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:28:08.073+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:28:08.059+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:28:08.078+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:28:08.103+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.113 seconds
[2025-01-15T19:28:38.277+0000] {processor.py:186} INFO - Started process (PID=717) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:28:38.279+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:28:38.282+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:28:38.281+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:28:38.349+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:28:38.337+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:28:38.355+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:28:38.382+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.110 seconds
[2025-01-15T19:29:08.933+0000] {processor.py:186} INFO - Started process (PID=781) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:29:08.934+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:29:08.938+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:29:08.937+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:29:09.002+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:29:08.992+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:29:09.007+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:29:09.030+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.102 seconds
[2025-01-15T19:29:39.116+0000] {processor.py:186} INFO - Started process (PID=845) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:29:39.118+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:29:39.120+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:29:39.120+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:29:39.184+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:29:39.172+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:29:39.188+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:29:39.214+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.108 seconds
[2025-01-15T19:30:09.678+0000] {processor.py:186} INFO - Started process (PID=909) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:30:09.681+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:30:09.684+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:30:09.683+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:30:09.751+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:30:09.739+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:30:09.755+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:30:09.786+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.120 seconds
[2025-01-15T19:30:40.064+0000] {processor.py:186} INFO - Started process (PID=973) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:30:40.065+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:30:40.068+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:30:40.068+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:30:40.135+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:30:40.121+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:30:40.140+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:30:40.164+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.106 seconds
[2025-01-15T19:31:10.586+0000] {processor.py:186} INFO - Started process (PID=1037) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:31:10.588+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:31:10.596+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:31:10.593+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:31:10.671+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:31:10.659+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:31:10.675+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:31:10.720+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.141 seconds
[2025-01-15T19:31:40.829+0000] {processor.py:186} INFO - Started process (PID=1101) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:31:40.830+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:31:40.833+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:31:40.833+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:31:40.897+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:31:40.887+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:31:40.902+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:31:40.925+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.101 seconds
[2025-01-15T19:32:11.355+0000] {processor.py:186} INFO - Started process (PID=1165) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:32:11.356+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:32:11.360+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:32:11.360+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:32:11.445+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:32:11.429+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:32:11.450+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:32:11.475+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.128 seconds
[2025-01-15T19:32:41.553+0000] {processor.py:186} INFO - Started process (PID=1229) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:32:41.554+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:32:41.557+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:32:41.557+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:32:41.625+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:32:41.614+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:32:41.630+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:32:41.657+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.110 seconds
[2025-01-15T19:33:12.469+0000] {processor.py:186} INFO - Started process (PID=1299) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:33:12.470+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:33:12.473+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:33:12.473+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:33:12.541+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:33:12.529+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:33:12.546+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:33:12.568+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.105 seconds
[2025-01-15T19:33:42.675+0000] {processor.py:186} INFO - Started process (PID=1363) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:33:42.677+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:33:42.680+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:33:42.679+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:33:42.752+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:33:42.738+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:33:42.756+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:33:42.781+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.113 seconds
[2025-01-15T19:34:13.629+0000] {processor.py:186} INFO - Started process (PID=1427) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:34:13.630+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:34:13.634+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:34:13.634+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:34:13.705+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:34:13.692+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:34:13.709+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:34:13.731+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.110 seconds
[2025-01-15T19:34:43.812+0000] {processor.py:186} INFO - Started process (PID=1491) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:34:43.813+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:34:43.817+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:34:43.817+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:34:43.891+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:34:43.877+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:34:43.896+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:34:43.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.114 seconds
[2025-01-15T19:35:14.085+0000] {processor.py:186} INFO - Started process (PID=1555) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:35:14.086+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:35:14.089+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:35:14.089+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:35:14.158+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:35:14.144+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:35:14.162+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:35:14.185+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.107 seconds
[2025-01-15T19:35:44.333+0000] {processor.py:186} INFO - Started process (PID=1619) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:35:44.334+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:35:44.337+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:35:44.337+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:35:44.407+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:35:44.395+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:35:44.412+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:35:44.435+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.108 seconds
[2025-01-15T19:36:14.844+0000] {processor.py:186} INFO - Started process (PID=1683) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:36:14.846+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:36:14.861+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:36:14.860+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:36:14.945+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:36:14.930+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:36:14.950+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:36:14.975+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.139 seconds
[2025-01-15T19:36:45.076+0000] {processor.py:186} INFO - Started process (PID=1747) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:36:45.078+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:36:45.082+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:36:45.081+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:36:45.150+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:36:45.139+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:36:45.155+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:36:45.187+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.115 seconds
[2025-01-15T19:37:15.857+0000] {processor.py:186} INFO - Started process (PID=1810) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:37:15.858+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:37:15.861+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:37:15.860+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:37:15.932+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:37:15.921+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:37:15.937+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:37:15.960+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.110 seconds
[2025-01-15T19:37:46.365+0000] {processor.py:186} INFO - Started process (PID=1874) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:37:46.367+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:37:46.370+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:37:46.370+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:37:46.437+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:37:46.424+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:37:46.442+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:37:46.470+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.110 seconds
[2025-01-15T19:38:16.603+0000] {processor.py:186} INFO - Started process (PID=1937) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:38:16.605+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:38:16.608+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:38:16.608+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:38:16.674+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:38:16.663+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:38:16.678+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:38:16.703+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.105 seconds
[2025-01-15T19:38:47.177+0000] {processor.py:186} INFO - Started process (PID=2000) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:38:47.178+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:38:47.182+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:38:47.182+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:38:47.249+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:38:47.237+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:38:47.254+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:38:47.281+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.112 seconds
[2025-01-15T19:39:17.481+0000] {processor.py:186} INFO - Started process (PID=2064) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:39:17.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:39:17.485+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:39:17.485+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:39:17.551+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:39:17.539+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:39:17.556+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:39:17.580+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.104 seconds
[2025-01-15T19:39:47.818+0000] {processor.py:186} INFO - Started process (PID=2128) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:39:47.819+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:39:47.822+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:39:47.822+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:39:47.903+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:39:47.892+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:39:47.908+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:39:47.941+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.130 seconds
[2025-01-15T19:40:18.501+0000] {processor.py:186} INFO - Started process (PID=2192) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:40:18.503+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:40:18.506+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:40:18.505+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:40:18.565+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:40:18.555+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:40:18.570+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:40:18.595+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.099 seconds
[2025-01-15T19:40:48.768+0000] {processor.py:186} INFO - Started process (PID=2256) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:40:48.770+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:40:48.773+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:40:48.772+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:40:48.832+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:40:48.822+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:40:48.837+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:40:48.860+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.098 seconds
[2025-01-15T19:41:19.807+0000] {processor.py:186} INFO - Started process (PID=2320) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:41:19.809+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:41:19.813+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:41:19.812+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:41:19.880+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:41:19.869+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:41:19.884+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:41:19.911+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.113 seconds
[2025-01-15T19:41:50.243+0000] {processor.py:186} INFO - Started process (PID=2381) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:41:50.244+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:41:50.247+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:41:50.247+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:41:50.319+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:41:50.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:41:50.324+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:41:50.347+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.112 seconds
[2025-01-15T19:42:20.792+0000] {processor.py:186} INFO - Started process (PID=2445) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:42:20.793+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:42:20.796+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:42:20.796+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:42:20.853+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:42:20.844+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:42:20.857+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:42:20.881+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.096 seconds
[2025-01-15T19:42:51.761+0000] {processor.py:186} INFO - Started process (PID=2509) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:42:51.762+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:42:51.765+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:42:51.764+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:42:51.829+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:42:51.817+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:42:51.834+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:42:51.857+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.101 seconds
[2025-01-15T19:43:21.976+0000] {processor.py:186} INFO - Started process (PID=2573) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:43:21.977+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:43:21.980+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:43:21.980+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:43:22.049+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:43:22.037+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:43:22.055+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:43:22.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.118 seconds
[2025-01-15T19:43:52.246+0000] {processor.py:186} INFO - Started process (PID=2637) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:43:52.247+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:43:52.250+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:43:52.250+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:43:52.320+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:43:52.306+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:43:52.326+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:43:52.352+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.113 seconds
[2025-01-15T19:44:22.500+0000] {processor.py:186} INFO - Started process (PID=2701) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:44:22.501+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:44:22.504+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:44:22.503+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:44:22.571+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:44:22.560+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:44:22.576+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:44:22.598+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.104 seconds
[2025-01-15T19:44:52.795+0000] {processor.py:186} INFO - Started process (PID=2765) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:44:52.796+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:44:52.799+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:44:52.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:44:52.870+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:44:52.858+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:44:52.876+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:44:52.902+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.113 seconds
[2025-01-15T19:45:23.775+0000] {processor.py:186} INFO - Started process (PID=2829) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:45:23.776+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:45:23.779+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:45:23.778+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:45:23.850+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:45:23.836+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:45:23.855+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:45:23.879+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.110 seconds
[2025-01-15T19:45:54.256+0000] {processor.py:186} INFO - Started process (PID=2893) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:45:54.258+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:45:54.261+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:45:54.261+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:45:54.341+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:45:54.328+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:45:54.347+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:45:54.374+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.123 seconds
[2025-01-15T19:46:24.635+0000] {processor.py:186} INFO - Started process (PID=2957) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:46:24.637+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:46:24.640+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:46:24.639+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:46:24.717+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:46:24.702+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:46:24.721+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:46:24.748+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.120 seconds
[2025-01-15T19:46:55.323+0000] {processor.py:186} INFO - Started process (PID=3021) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:46:55.324+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:46:55.328+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:46:55.327+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:46:55.401+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:46:55.387+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:46:55.406+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:46:55.431+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.113 seconds
[2025-01-15T19:47:25.713+0000] {processor.py:186} INFO - Started process (PID=3085) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:47:25.714+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:47:25.716+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:47:25.716+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:47:25.777+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:47:25.767+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:47:25.782+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:47:25.805+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.098 seconds
[2025-01-15T19:47:56.356+0000] {processor.py:186} INFO - Started process (PID=3149) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:47:56.357+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:47:56.359+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:47:56.359+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:47:56.430+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:47:56.417+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:47:56.434+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:47:56.459+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.109 seconds
[2025-01-15T19:48:27.185+0000] {processor.py:186} INFO - Started process (PID=3213) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:48:27.187+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:48:27.189+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:48:27.189+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:48:27.250+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:48:27.241+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:48:27.255+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:48:27.280+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.100 seconds
[2025-01-15T19:48:58.156+0000] {processor.py:186} INFO - Started process (PID=3277) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:48:58.157+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:48:58.160+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:48:58.159+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:48:58.228+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:48:58.215+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:48:58.233+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:48:58.261+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.111 seconds
[2025-01-15T19:49:28.924+0000] {processor.py:186} INFO - Started process (PID=3341) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:49:28.926+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:49:28.930+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:49:28.929+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:49:28.997+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:49:28.986+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:49:29.002+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:49:29.033+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.119 seconds
[2025-01-15T19:49:59.439+0000] {processor.py:186} INFO - Started process (PID=3405) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:49:59.440+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:49:59.442+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:49:59.442+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:49:59.505+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:49:59.493+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:49:59.510+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:49:58.915+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.103 seconds
[2025-01-15T19:50:29.026+0000] {processor.py:186} INFO - Started process (PID=3472) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:50:29.028+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:50:29.031+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:50:29.031+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:50:29.097+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:50:29.087+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:50:29.101+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:50:29.124+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.103 seconds
[2025-01-15T19:50:59.236+0000] {processor.py:186} INFO - Started process (PID=3534) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:50:59.237+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:50:59.240+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:50:59.239+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:50:59.310+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:50:59.296+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:50:59.314+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:50:59.346+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.116 seconds
[2025-01-15T19:51:30.022+0000] {processor.py:186} INFO - Started process (PID=3597) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:51:30.024+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:51:30.028+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:51:30.027+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:51:30.094+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:51:30.082+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:51:30.100+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:51:30.132+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.119 seconds
[2025-01-15T19:52:00.540+0000] {processor.py:186} INFO - Started process (PID=3667) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:52:00.542+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:52:00.544+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:52:00.544+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:52:00.607+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:52:00.595+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:52:00.612+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:52:00.634+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.101 seconds
[2025-01-15T19:52:30.926+0000] {processor.py:186} INFO - Started process (PID=3731) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:52:30.927+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:52:30.930+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:52:30.930+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:52:30.995+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:52:30.984+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:52:31.000+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:52:31.024+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.103 seconds
[2025-01-15T19:57:04.902+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:57:04.904+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:57:04.909+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:57:04.909+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:57:04.995+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:57:04.981+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:57:05.001+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:57:05.031+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.138 seconds
[2025-01-15T19:57:35.431+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:57:35.432+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:57:35.436+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:57:35.435+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:57:35.507+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:57:35.496+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:57:35.513+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:57:35.537+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.113 seconds
[2025-01-15T19:58:05.935+0000] {processor.py:186} INFO - Started process (PID=191) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:58:05.936+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:58:05.939+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:58:05.939+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:58:06.004+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:58:05.992+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:58:06.010+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:58:06.035+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.107 seconds
[2025-01-15T19:58:36.749+0000] {processor.py:186} INFO - Started process (PID=261) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:58:36.757+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:58:36.761+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:58:36.760+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:58:36.848+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:58:36.835+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:58:36.852+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:58:36.876+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.135 seconds
[2025-01-15T19:59:06.936+0000] {processor.py:186} INFO - Started process (PID=326) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:59:06.938+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:59:06.940+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:59:06.940+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:59:07.009+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:59:06.995+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:59:07.014+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:59:07.037+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.106 seconds
[2025-01-15T19:59:37.840+0000] {processor.py:186} INFO - Started process (PID=389) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T19:59:37.841+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T19:59:37.844+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:59:37.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:59:37.917+0000] {logging_mixin.py:190} INFO - [2025-01-15T19:59:37.905+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T19:59:37.921+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T19:59:37.946+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.112 seconds
[2025-01-15T20:00:08.647+0000] {processor.py:186} INFO - Started process (PID=453) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T20:00:08.648+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T20:00:08.653+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:00:08.652+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:00:08.739+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:00:08.722+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T20:00:08.746+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:00:08.778+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.140 seconds
[2025-01-15T20:00:39.075+0000] {processor.py:186} INFO - Started process (PID=517) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T20:00:39.077+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T20:00:39.080+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:00:39.080+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:00:39.147+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:00:39.137+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T20:00:39.152+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:00:39.179+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.111 seconds
[2025-01-15T20:01:09.675+0000] {processor.py:186} INFO - Started process (PID=581) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T20:01:09.677+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T20:01:09.680+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:01:09.680+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:01:09.750+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:01:09.738+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T20:01:09.756+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:01:09.781+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.114 seconds
[2025-01-15T20:01:39.839+0000] {processor.py:186} INFO - Started process (PID=645) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T20:01:39.840+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T20:01:39.844+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:01:39.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:01:39.918+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:01:39.905+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T20:01:39.923+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:01:39.960+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.129 seconds
[2025-01-15T20:02:10.575+0000] {processor.py:186} INFO - Started process (PID=709) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T20:02:10.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T20:02:10.582+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:02:10.582+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:02:10.653+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:02:10.639+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T20:02:10.658+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:02:10.681+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.113 seconds
[2025-01-15T20:02:41.088+0000] {processor.py:186} INFO - Started process (PID=773) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T20:02:41.090+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T20:02:41.094+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:02:41.093+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:02:41.167+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:02:41.154+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T20:02:41.172+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:02:41.204+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.126 seconds
[2025-01-15T20:03:11.617+0000] {processor.py:186} INFO - Started process (PID=837) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T20:03:11.618+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T20:03:11.621+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:03:11.621+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:03:11.691+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:03:11.679+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T20:03:11.695+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:03:11.723+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.111 seconds
[2025-01-15T20:03:41.965+0000] {processor.py:186} INFO - Started process (PID=901) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T20:03:41.967+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T20:03:41.969+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:03:41.969+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:03:42.037+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:03:42.027+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T20:03:42.043+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:03:42.066+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.107 seconds
[2025-01-15T20:04:12.831+0000] {processor.py:186} INFO - Started process (PID=965) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T20:04:12.832+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T20:04:12.835+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:04:12.835+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:04:12.902+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:04:12.890+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T20:04:12.907+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:04:12.931+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.105 seconds
[2025-01-15T20:04:43.438+0000] {processor.py:186} INFO - Started process (PID=1029) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T20:04:43.439+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T20:04:43.442+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:04:43.442+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:04:43.515+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:04:43.502+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T20:04:43.522+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:04:43.556+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.123 seconds
[2025-01-15T20:05:13.959+0000] {processor.py:186} INFO - Started process (PID=1093) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T20:05:13.960+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T20:05:13.964+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:05:13.964+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:05:14.034+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:05:14.020+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T20:05:14.038+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:05:14.062+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.114 seconds
[2025-01-15T20:05:44.393+0000] {processor.py:186} INFO - Started process (PID=1157) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T20:05:44.394+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T20:05:44.397+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:05:44.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:05:44.461+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:05:44.450+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T20:05:44.465+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:05:44.495+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.109 seconds
[2025-01-15T20:06:15.100+0000] {processor.py:186} INFO - Started process (PID=1221) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T20:06:15.102+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T20:06:15.105+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:06:15.105+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:06:15.177+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:06:15.164+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T20:06:15.183+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:06:15.206+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.112 seconds
[2025-01-15T20:06:45.637+0000] {processor.py:186} INFO - Started process (PID=1291) to work on /opt/airflow/dags/hw_dag.py
[2025-01-15T20:06:45.639+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2025-01-15T20:06:45.641+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:06:45.641+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:06:45.707+0000] {logging_mixin.py:190} INFO - [2025-01-15T20:06:45.696+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-15T20:06:45.712+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2025-01-15T20:06:45.736+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.105 seconds
