[2025-01-17T10:37:27.776+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:37:27.778+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T10:37:27.783+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:37:27.782+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:37:27.920+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:37:27.902+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-17T10:37:27.927+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:37:27.977+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.208 seconds
[2025-01-17T10:37:58.328+0000] {processor.py:186} INFO - Started process (PID=133) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:37:58.330+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T10:37:58.337+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:37:58.336+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:37:58.439+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:37:58.423+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-17T10:37:58.446+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:37:58.489+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.176 seconds
[2025-01-17T10:38:29.128+0000] {processor.py:186} INFO - Started process (PID=197) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:38:29.131+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T10:38:29.139+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:38:29.137+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:38:29.298+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:38:29.271+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 16, in <module>
    from modules.pipeline import pipeline
  File "/opt/airflow/modules/pipeline.py", line 7, in <module>
    from sklearn.compose import ColumnTransformer, make_column_selector
ModuleNotFoundError: No module named 'sklearn'
[2025-01-17T10:38:29.316+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:38:29.404+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.294 seconds
[2025-01-17T10:52:11.434+0000] {processor.py:186} INFO - Started process (PID=70) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:52:11.436+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T10:52:11.440+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:52:11.440+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:52:11.468+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:52:11.462+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T10:52:11.470+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:52:11.504+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.079 seconds
[2025-01-17T10:52:41.684+0000] {processor.py:186} INFO - Started process (PID=134) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:52:41.685+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T10:52:41.689+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:52:41.689+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:52:41.710+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:52:41.705+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T10:52:41.712+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:52:41.745+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.067 seconds
[2025-01-17T10:53:12.316+0000] {processor.py:186} INFO - Started process (PID=198) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:53:12.317+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T10:53:12.320+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:53:12.319+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:53:12.343+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:53:12.338+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T10:53:12.345+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:53:12.377+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.067 seconds
[2025-01-17T10:53:42.880+0000] {processor.py:186} INFO - Started process (PID=262) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:53:42.882+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T10:53:42.886+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:53:42.885+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:53:42.916+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:53:42.910+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T10:53:42.918+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:53:42.947+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.076 seconds
[2025-01-17T10:54:13.128+0000] {processor.py:186} INFO - Started process (PID=327) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:54:13.129+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T10:54:13.132+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:54:13.132+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:54:13.157+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:54:13.152+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T10:54:13.160+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:54:13.192+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.071 seconds
[2025-01-17T10:54:43.446+0000] {processor.py:186} INFO - Started process (PID=391) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:54:43.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T10:54:43.451+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:54:43.451+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:54:43.474+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:54:43.470+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T10:54:43.477+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:54:43.510+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.069 seconds
[2025-01-17T10:55:13.801+0000] {processor.py:186} INFO - Started process (PID=455) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:55:13.802+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T10:55:13.805+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:55:13.805+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:55:13.824+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:55:13.821+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T10:55:13.826+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:55:13.857+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.064 seconds
[2025-01-17T10:55:44.177+0000] {processor.py:186} INFO - Started process (PID=519) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:55:44.178+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T10:55:44.181+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:55:44.181+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:55:44.205+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:55:44.200+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T10:55:44.208+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:55:44.239+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.067 seconds
[2025-01-17T10:56:14.558+0000] {processor.py:186} INFO - Started process (PID=584) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:56:14.560+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T10:56:14.563+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:56:14.562+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:56:14.586+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:56:14.580+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T10:56:14.587+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:56:14.619+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.066 seconds
[2025-01-17T10:56:45.073+0000] {processor.py:186} INFO - Started process (PID=648) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:56:45.074+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T10:56:45.079+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:56:45.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:56:45.108+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:56:45.104+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T10:56:45.110+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:56:45.141+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.074 seconds
[2025-01-17T10:57:15.953+0000] {processor.py:186} INFO - Started process (PID=719) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:57:15.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T10:57:15.957+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:57:15.956+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:57:15.978+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:57:15.973+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T10:57:15.981+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:57:16.014+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.066 seconds
[2025-01-17T10:57:46.474+0000] {processor.py:186} INFO - Started process (PID=783) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:57:46.475+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T10:57:46.478+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:57:46.477+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:57:46.501+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:57:46.496+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T10:57:46.503+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:57:46.525+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.058 seconds
[2025-01-17T10:58:17.210+0000] {processor.py:186} INFO - Started process (PID=847) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:58:17.211+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T10:58:17.214+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:58:17.213+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:58:17.237+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:58:17.233+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T10:58:17.240+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:58:17.264+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.060 seconds
[2025-01-17T10:58:48.120+0000] {processor.py:186} INFO - Started process (PID=911) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:58:48.121+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T10:58:48.124+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:58:48.123+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:58:48.147+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:58:48.142+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T10:58:48.150+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:58:48.173+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.059 seconds
[2025-01-17T10:59:18.407+0000] {processor.py:186} INFO - Started process (PID=975) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:59:18.409+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T10:59:18.411+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:59:18.411+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:59:18.436+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:59:18.431+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T10:59:18.438+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:59:18.461+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.060 seconds
[2025-01-17T10:59:49.365+0000] {processor.py:186} INFO - Started process (PID=1039) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:59:49.366+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T10:59:49.369+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:59:49.369+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:59:49.393+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:59:49.388+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 16, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T10:59:49.396+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T10:59:49.418+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.060 seconds
[2025-01-17T11:21:59.212+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:21:59.214+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T11:21:59.219+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:21:59.218+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:21:59.266+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:21:59.257+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 13, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T11:21:59.269+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:21:59.301+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.100 seconds
[2025-01-17T11:22:29.994+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:22:29.995+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T11:22:29.997+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:22:29.997+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:22:30.024+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:22:30.019+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 13, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T11:22:30.026+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:22:30.059+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.071 seconds
[2025-01-17T11:23:00.290+0000] {processor.py:186} INFO - Started process (PID=191) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:23:00.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T11:23:00.294+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:23:00.294+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:23:00.316+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:23:00.311+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 13, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T11:23:00.318+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:23:00.341+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.056 seconds
[2025-01-17T11:23:30.723+0000] {processor.py:186} INFO - Started process (PID=255) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:23:30.724+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T11:23:30.728+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:23:30.727+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:23:30.755+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:23:30.750+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 13, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T11:23:30.758+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:23:30.792+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.076 seconds
[2025-01-17T11:24:01.109+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:24:01.110+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T11:24:01.113+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:24:01.112+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:24:01.145+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:24:01.141+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 13, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T11:24:01.148+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:24:01.176+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.073 seconds
[2025-01-17T11:24:31.545+0000] {processor.py:186} INFO - Started process (PID=383) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:24:31.547+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T11:24:31.551+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:24:31.551+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:24:31.575+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:24:31.569+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 13, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T11:24:31.577+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:24:31.601+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.064 seconds
[2025-01-17T11:25:01.653+0000] {processor.py:186} INFO - Started process (PID=447) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:25:01.655+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T11:25:01.659+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:25:01.659+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:25:01.682+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:25:01.678+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 13, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T11:25:01.684+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:25:01.715+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.066 seconds
[2025-01-17T11:25:32.309+0000] {processor.py:186} INFO - Started process (PID=511) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:25:32.311+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T11:25:32.314+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:25:32.313+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:25:32.336+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:25:32.331+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 13, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T11:25:32.338+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:25:32.360+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.057 seconds
[2025-01-17T11:26:03.151+0000] {processor.py:186} INFO - Started process (PID=582) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:26:03.153+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T11:26:03.155+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:26:03.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:26:03.175+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:26:03.171+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 13, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T11:26:03.177+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:26:03.209+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.062 seconds
[2025-01-17T11:26:33.621+0000] {processor.py:186} INFO - Started process (PID=646) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:26:33.622+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T11:26:33.626+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:26:33.626+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:26:33.651+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:26:33.646+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 13, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T11:26:33.654+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:26:33.678+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.063 seconds
[2025-01-17T11:27:03.740+0000] {processor.py:186} INFO - Started process (PID=710) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:27:03.742+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T11:27:03.746+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:27:03.745+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:27:03.774+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:27:03.769+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 13, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T11:27:03.776+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:27:03.806+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.072 seconds
[2025-01-17T11:27:34.309+0000] {processor.py:186} INFO - Started process (PID=774) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:27:34.310+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T11:27:34.313+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:27:34.312+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:27:34.338+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:27:34.332+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 13, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T11:27:34.341+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:27:34.366+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.062 seconds
[2025-01-17T11:28:05.021+0000] {processor.py:186} INFO - Started process (PID=838) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:28:05.023+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T11:28:05.026+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:28:05.025+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:28:05.049+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:28:05.045+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 13, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T11:28:05.051+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:28:05.074+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.059 seconds
[2025-01-17T11:28:36.007+0000] {processor.py:186} INFO - Started process (PID=903) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:28:36.008+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T11:28:36.011+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:28:36.010+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:28:36.033+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:28:36.028+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 13, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T11:28:36.036+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:28:36.058+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.057 seconds
[2025-01-17T11:29:06.886+0000] {processor.py:186} INFO - Started process (PID=967) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:29:06.888+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T11:29:06.892+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:29:06.892+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:29:06.918+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:29:06.912+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 13, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T11:29:06.920+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:29:06.957+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.079 seconds
[2025-01-17T11:29:37.239+0000] {processor.py:186} INFO - Started process (PID=1031) to work on /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:29:37.241+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hw_dag1.py for tasks to queue
[2025-01-17T11:29:37.245+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:29:37.245+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:29:37.293+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:29:37.273+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/hw_dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag1.py", line 13, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2025-01-17T11:29:37.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag1.py
[2025-01-17T11:29:37.378+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hw_dag1.py took 0.147 seconds
